version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_ENV=development
    stdin_open: true
    tty: true
    networks:
      - dev-network

  # Mock API server for development
  api-mock:
    image: node:18-alpine
    ports:
      - "3001:3001"
    volumes:
      - ./mock-api:/app
    working_dir: /app
    command: ["node", "server.js"]
    environment:
      - NODE_ENV=development
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge